#!/usr/bin/env bash
#
# audit_etl_roadmap_drift.sh — Detect drift between etl-architecture-roadmap
# closure recommendations and actual spectra change / GitHub milestone state.
#
# Per etl-architecture-roadmap spec Failure modes section + design Risk 4
# mitigation.
#
# Triggered by: quarterly recurring iCloud reminders (2026-08-01 / 2026-11-01 /
# 2027-02-01 / 2027-05-01) per /spectra-apply etl-master-sequencing Task 6.1
#
# Usage:
#   bash audit_etl_roadmap_drift.sh                # Print drift report to stdout
#   bash audit_etl_roadmap_drift.sh > report.md   # Capture to file
#
# Output: markdown report with:
#   - Per in-flight change: actual phase vs roadmap recommendation
#   - DRIFT WARNINGS for changes whose actual disposition diverged
#   - Suggested IC_R011 follow-up issues to file

set -e

# Resolve paths — script at shared/global_scripts/00_principles/changelog/scripts/
# Walk up 5 levels: scripts/ → changelog/ → 00_principles/ → global_scripts/ → shared/ → l4_enterprise/
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
L4_ENTERPRISE_DIR="$(cd "$SCRIPT_DIR/../../../../.." && pwd)"
GH_REPO="kiki830621/ai_martech_global_scripts"

# Sanity check
if [ ! -d "$L4_ENTERPRISE_DIR/openspec/specs/etl-architecture-roadmap" ] && \
   [ ! -d "$L4_ENTERPRISE_DIR/openspec/changes/etl-master-sequencing" ]; then
  echo "ERROR: Cannot locate etl-architecture-roadmap spec or master change"
  echo "  Expected: $L4_ENTERPRISE_DIR/openspec/specs/etl-architecture-roadmap/"
  echo "       OR: $L4_ENTERPRISE_DIR/openspec/changes/etl-master-sequencing/"
  exit 2
fi

# ---------------------------------------------------------------------------
# Roadmap closure recommendations (from spec Requirement 5)
# ---------------------------------------------------------------------------
# Format: <change-name>:<expected-disposition>
# Disposition: push-to-done | absorb-into-child | keep-open-until-P3
declare -a EXPECTATIONS=(
  "bridge-end-to-end-realization:push-to-done"
  "glue-bridge-self-converging-review:push-to-done"
  "mp160-ai-authoring-completeness:push-to-done"
  "mp161-company-scoped-schemas:push-to-done"
  "fix-mamba-etl-complete-capture:keep-open-until-P3"
  "metadata-to-meta-data-duckdb:push-to-done"
  "autoinit-failfast-smart-cache:push-to-done"
  "unify-cross-driver-query-layer:push-to-done"
  "dev-r056-r-first-language:push-to-done"
  "qef-product-attribute-schema-fix:push-to-done"
  "qef-product-master-redesign:absorb-into-child"
  # qef-product-attribute-schemas was archived as 2026-04-29-qef-attribute-bridge-types-and-na-handling
  # before master plan; not tracked as live drift candidate here
  "qef-rpl-psg-coverage-bundle:absorb-into-child"
  "dashboard-presence-verification:keep-open-until-P3"
  "fix-mamba-dashboard-empty-data:keep-open-until-P3"
)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
TODAY=$(date +%Y-%m-%d)
echo "# ETL Roadmap Drift Audit Report"
echo ""
echo "> **Date**: $TODAY"
echo "> **Generated by**: \`audit_etl_roadmap_drift.sh\`"
echo "> **Spec reference**: \`openspec/specs/etl-architecture-roadmap/spec.md\` Requirement 5"
echo ""

# ---------------------------------------------------------------------------
# Section 1: Spectra change state vs expected disposition
# ---------------------------------------------------------------------------
echo "## Section 1: Per-change drift detection"
echo ""
echo "| Change | Expected | Actual State | Drift? | Notes |"
echo "|---|---|---|---|---|"

DRIFT_COUNT=0
WARNINGS=()

cd "$L4_ENTERPRISE_DIR" || exit 1

# Get current spectra state
CHANGES_JSON=$(spectra list --json 2>/dev/null || echo '{"changes":[]}')

for entry in "${EXPECTATIONS[@]}"; do
  CHANGE_NAME="${entry%%:*}"
  EXPECTED="${entry##*:}"

  # Check if change exists in active list
  ACTUAL=$(echo "$CHANGES_JSON" | python3 -c "
import json,sys
data = json.load(sys.stdin)
for c in data.get('changes',[]):
    if c['name'] == '$CHANGE_NAME':
        print(f\"{c['status']}:{c.get('completedTasks',0)}/{c.get('totalTasks',0)}\")
        sys.exit(0)
print('not-found-in-active')
")

  # Determine drift
  DRIFT="no"
  NOTES=""

  case "$EXPECTED" in
    push-to-done)
      if [[ "$ACTUAL" == not-found* ]]; then
        # check archive
        if ls "$L4_ENTERPRISE_DIR/openspec/changes/archive/" 2>/dev/null | grep -q "$CHANGE_NAME"; then
          NOTES="archived (expected outcome)"
        else
          NOTES="not in active or archive — possible rename"
          DRIFT="suspected"
          WARNINGS+=("$CHANGE_NAME: not found anywhere — verify name")
          DRIFT_COUNT=$((DRIFT_COUNT + 1))
        fi
      elif [[ "$ACTUAL" == done:* ]]; then
        NOTES="done (expected outcome)"
      elif [[ "$ACTUAL" == in-progress:* ]]; then
        NOTES="still in-progress"
      fi
      ;;
    absorb-into-child)
      if [[ "$ACTUAL" == not-found* ]]; then
        if ls "$L4_ENTERPRISE_DIR/openspec/changes/archive/" 2>/dev/null | grep -q "$CHANGE_NAME"; then
          NOTES="archived (P3 child may have absorbed)"
        else
          NOTES="missing"
          DRIFT="yes"
          WARNINGS+=("$CHANGE_NAME: expected absorb-into-child but not found")
          DRIFT_COUNT=$((DRIFT_COUNT + 1))
        fi
      elif [[ "$ACTUAL" == done:* ]]; then
        NOTES="done as standalone (not absorbed) — possible drift"
        DRIFT="suspected"
        WARNINGS+=("$CHANGE_NAME: closed as standalone, expected absorb into P3 child")
        DRIFT_COUNT=$((DRIFT_COUNT + 1))
      else
        # check absorb_note.md exists
        if [ -f "$L4_ENTERPRISE_DIR/openspec/changes/$CHANGE_NAME/absorb_note.md" ]; then
          NOTES="in-progress + absorb_note.md present"
        else
          NOTES="in-progress, no absorb_note.md"
          WARNINGS+=("$CHANGE_NAME: missing absorb_note.md")
        fi
      fi
      ;;
    keep-open-until-P3)
      if [[ "$ACTUAL" == done:* ]]; then
        NOTES="closed before P3 ship — verify P3 done"
        DRIFT="suspected"
        WARNINGS+=("$CHANGE_NAME: closed before P3 verification — verify P3 child shipped")
        DRIFT_COUNT=$((DRIFT_COUNT + 1))
      elif [[ "$ACTUAL" == not-found* ]]; then
        if ls "$L4_ENTERPRISE_DIR/openspec/changes/archive/" 2>/dev/null | grep -q "$CHANGE_NAME"; then
          NOTES="archived — verify P3 done"
        else
          NOTES="missing"
          DRIFT="yes"
          WARNINGS+=("$CHANGE_NAME: missing entirely")
          DRIFT_COUNT=$((DRIFT_COUNT + 1))
        fi
      else
        NOTES="open as expected"
      fi
      ;;
  esac

  echo "| \`$CHANGE_NAME\` | $EXPECTED | $ACTUAL | $DRIFT | $NOTES |"
done

# ---------------------------------------------------------------------------
# Section 2: GitHub milestone state
# ---------------------------------------------------------------------------
echo ""
echo "## Section 2: GitHub milestone progress"
echo ""

if command -v gh >/dev/null 2>&1; then
  echo "| Milestone | Open | Closed | Total | Notes |"
  echo "|---|---:|---:|---:|---|"
  for ms in P0-stabilize P1-vocabulary-realignment P2-skill-redesign P3-aggressive-migration; do
    OPEN=$(gh issue list --repo "$GH_REPO" --milestone "$ms" --state open --json number 2>/dev/null | python3 -c "import json,sys; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "?")
    CLOSED=$(gh issue list --repo "$GH_REPO" --milestone "$ms" --state closed --json number 2>/dev/null | python3 -c "import json,sys; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "?")
    if [ "$OPEN" != "?" ] && [ "$CLOSED" != "?" ]; then
      TOTAL=$((OPEN + CLOSED))
    else
      TOTAL="?"
    fi
    echo "| $ms | $OPEN | $CLOSED | $TOTAL | |"
  done
else
  echo "(gh CLI not available — skip milestone scan)"
fi

# ---------------------------------------------------------------------------
# Section 3: Drift summary + recommended follow-up issues
# ---------------------------------------------------------------------------
echo ""
echo "## Section 3: Drift summary"
echo ""

if [ "$DRIFT_COUNT" -eq 0 ]; then
  echo "**No drift detected.** ✓"
  echo ""
  echo "All 16 in-flight changes match their roadmap closure recommendations."
else
  echo "**Drift detected: $DRIFT_COUNT items**"
  echo ""
  echo "### Warnings"
  echo ""
  for warn in "${WARNINGS[@]}"; do
    echo "- ⚠ $warn"
  done
  echo ""
  echo "### Recommended follow-up actions (per IC_R011)"
  echo ""
  echo "For each drifted item, file follow-up issue: \`/idd-issue\` with body:"
  echo ""
  echo "    [refactor] Amend etl-architecture-roadmap closure recommendation for <change-name>"
  echo ""
  echo "    Drift detected on $TODAY by audit_etl_roadmap_drift.sh:"
  echo "    - Expected: <expected disposition>"
  echo "    - Actual: <actual state>"
  echo "    - Suggested amendment: <reclassify to ... OR mark drifted-acceptable>"
fi

# ---------------------------------------------------------------------------
# Exit code: 0 if no drift, 1 if drift detected (for CI integration)
# ---------------------------------------------------------------------------
exit $DRIFT_COUNT
